### ISSUE TITLE
typings now generate typings/index.d.ts and not typings/main.d.ts

### ISSUE THREAD

**Issue by ykoehler** [deeleman/angular2-essentials#11]
After installing es6-shim the typings folder contains:

```
$ ls -lR typings
typings:
total 8
drwxr-xr-x 3 ykoehler ykoehler 4096 Jun 10 11:45 globals
-rw-r--r-- 1 ykoehler ykoehler   53 Jun 10 11:45 index.d.ts

typings/globals:
total 4
drwxr-xr-x 2 ykoehler ykoehler 4096 Jun 10 11:45 es6-shim

typings/globals/es6-shim:
total 28
-rw-r--r-- 1 ykoehler ykoehler 24289 Jun 10 11:45 index.d.ts
-rw-r--r-- 1 ykoehler ykoehler   392 Jun 10 11:45 typings.json
```

There is no main.d.ts anymore.

**Comment by deeleman** [comment]
As mentioned already at #10, the release of version 1.x of the TypeScript Definition Manager, right after the book launch, introduced a handful of relevant breaking changes :

> `browser.d.ts` is removed, so now all definition typings are accessible from one single entry point: `index.d.ts`. This removes the need to exclude `typings/main` and `typings/main.d.ts` from `tsconfig.json` anymore.

Although this does not break the current code implementation, the GitHub repository will reflect this new update in a few days. 

Thanks for contributing.
