### ISSUE TITLE
error regarding importing the component module into index.html in book

### ISSUE THREAD

**Issue by cloverharvest** [deeleman/angular2-essentials#14]
TYPO. 

In Ch:1's Hello Angular2!, Section: Putting it all together, the book 's code reads:

// Here we import the component module
      // with no file extension
      System.import ('built/hello-angular');
    </script>

Please add opening script tag, like so:

```
   <script>
      System.import ('built/hello-angular');
    </script>
```

And  "Hello Angular 2!" should display on the localhost:3000 page.
# 

This took  me a while to figure out, but it helped me put my self back on track. 

Might be helpful to other readers too. 

Looking forward to finish the book and build a pomodoro app. Thanks!

**Comment by deeleman** [comment]
Yep, just reviewed the code block and confirmed the issue. Thanks for noticing!

Please do not hesitate on opening a new issue if you stumble upon any other typo. Thanks in advance!
