### ISSUE TITLE
Chapter 1 - can't get it to work

### ISSUE THREAD

**Issue by vulkanino** [deeleman/angular2-essentials#16]
Hello,

I am following chapter 1 but nothing shows on the homepage (blank page). Console is empty.
Here's the Plunker:

https://plnkr.co/edit/OGQrwXNEIXcFHqgG0C5f?p=info

What am I doing wrong?
Thanks.

**Comment by vulkanino** [comment]
Sorry, I've sorted it out, it was here:

```
<script src="systemjs.config.js"></script>
<script>
        System.import('built/hello-angular')
            .then(null, console.error.bind(console));
</script>
```

There's a missing `<script>` in the book source (page 19).

**Comment by deeleman** [comment]
Yep, sorry for the late reply. Another reader pointed out this issue a few days ago and I'm still pending on allocating some time to publish the UPDATES/Errata page, where this and some other minor issues will be addressed. 

In the meantime do not hesitate on posting your questions here and thanks for contributing. Hope you're enjoying the reading.
