### ISSUE TITLE
Chapter 1 - strange css styles

### ISSUE THREAD

**Issue by vulkanino** [deeleman/angular2-essentials#18]
Copying the source at page 32 I get this:

![image](https://cloud.githubusercontent.com/assets/9436853/16519746/88998b4a-3f8b-11e6-8bd9-9fba18b3e980.png)

The caption is all displaced to the left. 
?

**Comment by deeleman** [comment]
I guess that you refer to the `My Pomodoro Timer` as _caption_. Well, that is the expected behavior of the `navbar-brand` elements in Bootstrap, so you can disregard it.

**Comment by vulkanino** [comment]
But in the book the result is different, the caption is centered, that's why I asked.
