### ISSUE TITLE
Chapter 1

### ISSUE THREAD

**Issue by simonwardle** [deeleman/angular2-essentials#23]
Hi @deeleman 
I have created a new thread like requested.
I have a new folder on my windows PC
If I download your package.json into my windows folder and run 'npm install'
Everything runs through and it looks successful in that I get the tree and just warnings.
But if I scroll up the tree I can see UNMET PEER DEPENDENCY rxjs@5.0.0-beta.10
This is also mentioned in the warnings at the end of the install but beta.6.
npm WARN @angular/http@2.0.0-rc.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.
npm WARN @angular/core@2.0.0-rc.4 requires a peer of rxjs@5.0.0-beta.6 but none was installed.

If I open hello-angular.ts and enter the code import {Component} from 'angular/core';
I notice the error "[ts] Cannot find module angular/core" (this is coming from Visual Studio Code)
This causes the tsc to fail with
import {Component} from 'angular/core';
Hope this helps.

**Comment by deeleman** [comment]
Most of the time those warnings can be disregarded. On the other hand the module paths have an `@`prepending the `angular` segment. So please replace:

`import { Component } from 'angular/core';`

by...

`import { Component } from '@angular/core';`

Last but not least: double check the package.json you just downloaded. The `http` package defined in the book repository is `@angular/http@2.0.0-rc.1` and not `@angular/http@2.0.0-rc.4`, so to my knowledge you shouldn't get any warning related to RC.4.
