### ISSUE TITLE
Chapter 04 - tooltip error

### ISSUE THREAD

**Issue by jim-coffey** [deeleman/angular2-essentials#24]
In the book, the tooltip paragraph is displayed/hidden with the following attribute logic :  

`*ngIf="queuedPomodoros > 0"`

However, this is leading to console.log errors when mousing over the tooltip : 

`ORIGINAL EXCEPTION: TypeError: Cannot set property 'innerText' of undefined`

Once the display/hide logic is updated to the code in the repo here the error goes away and the tooltip works as advertised : 

i.e. `[hidden]="queuedPomodoros === 0"`

It would be useful to get the book code updated to the code that works - but it might also be interesting to understand why one works and the other causes a bug in the tooltip hover action.

Is `*ngIf` actually removing/recreating the dom element and the code then loses it's reference to that element - while the updated code is just changing visibility classes, therefore the reference to the element is not lost?

**Comment by fourpastmidnight** [comment]
Hmm, after looking at this, I think the author meant to only show pomodoros for the queued task(s) and then, mousing over a pomodoro associated with a task would display that task name in the `<p>` below. But that wasn't happening at all. Your fix above allows the `mouseover` and `mouseout` to work, but all pomodoros are always shown for all tasks, irregardless of whether the tasks is "queued".

There seems to be a fundamental logic error in this part of the sample.

**Comment by fourpastmidnight** [comment]
Here's my changes, which are in addition to @jim-coffey's: Specify a `[hidden]` attribute on the `<pomodoro-task-icons>` element which hides the generated HTML if the task is not queued. With this change in place, when queuing a task, pomodoros are displayed according to the number of pomodoros required by the task. And mousing over the pomodoros displays the name of the task.

You can even queue more than one task and additional pomodoros will be displayed, and mousing over them will show the title for the corresponding task. I believe this was the original intent of the example. If it wasn't, well, IMHO, it should've been. :wink:

```html
<p>
    <span *ngFor="let queuedTask of tasks">
        <pomodoro-task-icons [task]="queuedTask" size="50" [hidden]="!queuedTask.queued" (mouseover)="tooltip.innerText = queuedTask.name" (mouseout)="tooltip.innerText = 'Mouse over for details'"></pomodoro-task-icons>
    </span>
</p>
<p #tooltip [hidden]="queuedPomodoros === 0">Mouse over for details</p>
```

**Comment by MarkovEvgeni** [comment]
The same issue is in my copy of this book. But I prefer the following solution:

Add 'hint' variable to the class TasksComponent:

```
class TasksComponent {
    today: Date;
    tasks: Task[];
    queuedPomodoros: number;
    hint: string;
    queueHeaderMapping: any = {
        '=0': 'No pomodoros',
        '=1': 'One pomodoro',
        'other': '# pomodoros'
    }
    
    constructor() {
        const tasksService: TaskService = new TaskService();
        this.tasks = tasksService.taskStore;
        this.today = new Date();
        this.updateQueuedPomodoros();
        this.hint = 'Mouseover for details';
    }
    
    toggleTask(task: Task): void {
        task.queued = !task.queued;
        this.updateQueuedPomodoros();
    }

    private updateQueuedPomodoros(): void {
        this.queuedPomodoros = this.tasks
            .filter((task: Task) => task.queued)
            .reduce((pomodoros: number, queuedTask: Task) => {
            return pomodoros + queuedTask.pomodorosRequired;
        }, 0);
    }

};
```
Change the following in the file named pomodoro-tasks.html 

```
<p>
     <span *ngFor="let queuedTask of tasks">
         <pomodoro-task-icons [task]="queuedTask"
              (mouseover)="hint = queuedTask.name"
              (mouseout)="hint = 'Mouseover for details'">
        </pomodoro-task-icons>
    </span>
</p>
<p #tooltip *ngIf="queuedPomodoros > 0">{{ hint }}</p>
```

Working well even with `*ngIf` directive.
