### ISSUE TITLE
No Compiler Warning

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#27]
In ch.2 s.04 you comment that if you try and perform a set action on a getter then the environment will give you a warning.  I don't get any warning at all either in the TypeScript playground or in Sublime 3 (with the TypeScript package installed).

This isn't really an issue, but I thought worth pointing out anyway.

Great book by the way.

**Comment by deeleman** [comment]
Yep, apparently the compiler has changed quite a lot in regards of warnings since that instance of the book was written (~v.1.0).

Thanks
