### ISSUE TITLE
Chapter 2 Section 6 - Module Resolution

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#29]
When I tried to import my external module with the line 
`import greetings = require('Greetings')`
it couldn't find the module.

I had to change the reference to the following to get it to work 
`import greetings = require('./Greetings');`

also in the example you have the following which fails as it isn't exposed in the module 
`var XmasGreetings = greetings.XmasGreetings();`

**Comment by deeleman** [comment]
Oops! Good catch, thanks!
