### ISSUE TITLE
Atom typescript package

### ISSUE THREAD

**Issue by sabas** [deeleman/angular2-essentials#3]
Page 13. Is this one the package?
https://atom.io/packages/atom-typescript

(for sublime you linked the plugin directly in the book)

Thanks!

**Comment by deeleman** [comment]
That's correct @sabas. Besides this one there is also a couple of useful extensions for live-linting your TypeScript code. I suggest to pair them up with the aforementioned extension to increase the quality of your code. Obviously I do not particularly endorse any specific extension and leave it up to you to try out them all and choose the one that better fits your needs.
