### ISSUE TITLE
Chapter 6 Section 4 Importing HTTP_PROVIDERS

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#33]
Once we start changing the service you state that the HTTTP_PROVIDERS (note, there is a typo) has already been injected at the top root component.  We never actually are instructed to make that change in the book.  I assume that we need the following in app.component.ts 

`import {HTTP_PROVIDERS} from '@angular/http';` and then in the providers 
`providers: [SHARED_PROVIDERS, HTTP_PROVIDERS],`

**Comment by deeleman** [comment]
It is actually instructed on page 177 ;)
