### ISSUE TITLE
Chapter 7 Section 2 - import from Angular2 ??

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#35]
At the beginning of the section you create the new `task-editor.component.ts` file and tell us to import from `angular2/core` and `angular2/router`.  These won't work, it needs to be `@angular/core` and `@angular/router-deprecated`

**Comment by deeleman** [comment]
That code snippet belongs to "Angular 2 Essentials", which was removed when the book evolved into "Learning Angular 2" and all the codebase got updated to RC.1.

When in doubt, please always refer tot he code available in this repo. thanks.
