### ISSUE TITLE
Chapter 7 Section 3 - Navigation changed

### ISSUE THREAD

**Issue by RichLinnell** [deeleman/angular2-essentials#36]
the first code change in this section made to the `task.component.ts` adds the index parameter to the route, but the route seems to have also been changed to 

`this.router.navigate(['Timer', { id: index }]);`

This is inconsistent with the end of the previous section where the route was defined as 

`this.router.navigate(['TimerComponent']);`

Immediately afterwards you go to the route definition and show it as follows, confirming the inconsistency 

`{  
     path: 'timer/:id',  
     name: 'TimerComponent',  
     component: TimerComponent}`

**Comment by deeleman** [comment]
Good catch, thank you so much!
