### ISSUE TITLE
Commands from page 8 failing 

### ISSUE THREAD

**Issue by AshwinKamathB** [deeleman/angular2-essentials#41]
E:\Angular2\learning-angular2>tsc --init --experimentalDecorators --emitDecorato
rMetadata --target ES5 --module system --moduleResolution node
error TS5023: Unknown option 'init'
Use the '--help' flag to see options.
error TS5023: Unknown option 'experimentalDecorators'
Use the '--help' flag to see options.
error TS5023: Unknown option 'emitDecoratorMetadata'
Use the '--help' flag to see options.
error TS5003: Module code generation 'system' not supported.
error TS5023: Unknown option 'moduleResolution'
Use the '--help' flag to see options.

tsc version 1.0.1.0

**Comment by turnipcyberveggie** [comment]
Have you tried 'tsc.cmd ..." ?

I found multiple installations of tsc, and needed to use tsc.cmd to use the latest version.

**Comment by deeleman** [comment]
You need at least TypeScript v1.8.1 to run the examples contained in the book. Version 1.0.x is too old and currently unsupported. Try to upgrade your Visual Studio edition should you're using the built-in compiler. 

Thanks.
