### ISSUE TITLE
Need to use tsc.cmd to get to latest version of tsc when Visual Studio is installed

### ISSUE THREAD

**Issue by turnipcyberveggie** [deeleman/angular2-essentials#42]
When following the installation steps the "tsc init..." command was failing. 

When "tsc -v" was run the version returned was "1.0.3.0", even though a newer version had been installed through npm. 

Running "where tsc" showed that tsc was installed in two places. The older version was from Visual Studio and the newer version was from npm. 

Running "tsc.cmd -v" resulted in 1.8.10, which was the expected version. 

Running the following command worked:
"tsc.cmd --init --experimentalDecorators --emitDecoratorMetadata --target ES5 --module system --moduleResolution node"

**Comment by deeleman** [comment]
You will definitely need at least TypeScript 1.8.10 to run the examples contained in the book (^2.0.2 once you move to Angular 2 Final, which you should definitely do though). I'm aware that the VS compiler has its own built-in compiler featuring its own version. 

You can either try updating VS or relying on the command line (whcih will obviously give you a more finegrained control as well)
