### ISSUE TITLE
Upgrades

### ISSUE THREAD

**Issue by tblnx** [deeleman/angular2-essentials#44]
I wonder when the promised upgrade of the end of june (:-) will be available. However I prefer a more recent upgrade of course that works with a more current version of Angular.
A nice book, that's for sure.
regards,
Ton

**Comment by deeleman** [comment]
I'm afraid everything has been set on a hiatus. I will not take part in a new edition of the book and Packt seems to be unable to find an author to take over the new edition or even provide me with support either way.

Now that Angular 4 Beta has been announced and bearing in mind the huge amount of work required to keep this repository fully up to date on each new release (mostly now that the entire book is no longer relevant), I'm afraid I cannot continue with this project on my own.

Thanks for your kind words.
