### ISSUE TITLE
Exception on npm start of Chapter 4

### ISSUE THREAD

**Issue by realEstateAdvisor** [deeleman/angular2-essentials#57]
Hi, 

I've downloaded the code, and opened with Visual Studio Code the chapter4 folder.
I've executed the npm install, and the npm start, but the system has raised this exception, in the attached log file.
Please let me know if I'm missing something or an help to fix this

Thanks

Antonio

[errorLog.txt](https://github.com/deeleman/learning-angular2/files/928550/errorLog.txt)

**Comment by re5pect123** [comment]
I have the some mistake. Please, put in order. Thx.

**Comment by deeleman** [comment]
The `concurrently` package has proved to cause issues and raise exceptions on the Windows OS. I'd recommend to remove its call from the `start` command. You can find more information at https://github.com/deeleman/learning-angular2/issues/40#issuecomment-244632848
