### ISSUE TITLE
npm install with -g may require higher privileges access, may want to add a note for that

### ISSUE THREAD

**Issue by ykoehler** [deeleman/angular2-essentials#8]
When using npm install -g typescript on linux it require privileges access.  On linux one may have to
do "sudo npm install -g typescript".  It was obvious for me but some people may get confused.

It may be helpful to add a note there to talk about this potential issue.

**Comment by deeleman** [comment]
There is actually such alert (although it is more geared towards Mac OS X users though) on page 8! 

All in all, the use of `sudo` is strongly discouraged addressing `EACCESS` issues upon [installing NPM packages globally](https://docs.npmjs.com/getting-started/installing-npm-packages-globally). You should fix your NPM permissions instead, which is something I strongly advice you to do in this case. Please refer to the following resource at NPM's site to fix your local permissions then: [How to fix npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions).

Thanks anyways for sharing your concerns! :)
