### ISSUE TITLE
Running tsc init didn't generate a rootDir or outDIr.

### ISSUE THREAD

**Issue by ykoehler** [deeleman/angular2-essentials#9]
Here is the output emitted in my tsconfig.json avec running the tsc init as specific in the book.

```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "target": "es5",
        "module": "system",
        "moduleResolution": "node",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}
```

Note the missing rootDir and outDir.

I doubt those are important, but since in your chapter you actually do mention them and talk explicitely about those two, you may need to put a note that they may or not appears in the generated tsconfig.json.

```
rootDir: This points to the folder the compiler will use to scan for TypeScript files to compile (currently the base folder in our example).
outDir: This defines where the compiled files will be moved unless we define our own output path by means of the --outDir parameter in the command line, the compiler will default to the built folder created at runtime in the same location where the tsconfig.json file lives.
```

**Comment by deeleman** [comment]
Good point. Will do for sure! :)

Thanks for noticing!

**Comment by stevefarwell** [comment]
same issue, I updated the file manually

**Comment by deeleman** [comment]
The TypeScript compiler evolved over the past months. While originally (at the time of writing this book) the `tsc init` command created `rootDir` and `outDir` properties, it removed those from the output at some stage. 

Now that everybody's well aware of this circumstance, let's close this issue.
